// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOtgnZS3tX4tfus_6Tb3ZAou9BjIimPes',
    appId: '1:621346416674:web:9bb370b60d4c7a34dd027b',
    messagingSenderId: '621346416674',
    projectId: 'educflow-ai',
    authDomain: 'educflow-ai.firebaseapp.com',
    storageBucket: 'educflow-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVcCwSPAps3aqcJq7B2X3mxxGr81T-b0',
    appId: '1:621346416674:android:ebdfb4dcdf7d41c8dd027b',
    messagingSenderId: '621346416674',
    projectId: 'educflow-ai',
    storageBucket: 'educflow-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoFtk7It2g_XA0uxqv-H8_Y0c7fr2ea8',
    appId: '1:621346416674:ios:86461168d1bb0caddd027b',
    messagingSenderId: '621346416674',
    projectId: 'educflow-ai',
    storageBucket: 'educflow-ai.firebasestorage.app',
    iosBundleId: 'com.martinrozas.eduflowai',
  );
}
